config/routes.rb
CurrencyRate::Application.routes.draw do
  root 'static_pages#calculate'
  match '/compute', to: 'static_pages#compute', via: :post
  match '/reload',  to: 'static_pages#reload',  via: :post

end

app/models/eur_usd_rate.rb
require 'open-uri'
require 'csv'

CSV_URI = 'https://sdw.ecb.europa.eu/quickviewexport.do?SERIES_KEY=120.EXR.D.USD.EUR.SP00.A&type=csv'
HEADER_SIZE = 5

class EurUsdRate < ActiveRecord::Base
	validates :date, presence: true, format: { with: /\d{4}-\d{2}-\d{2}/}, length: { is: 10 }, uniqueness: true
	validates :currency, numericality: true

	cattr_reader :data # for checking data

	def EurUsdRate.perform
		@@data = []
		@csv_file ||= csv_load_from_uri
		fill_in_db
	end

	def EurUsdRate.exchange(sum, rates)
		rates.map { |el| el * sum } 
	end

	def EurUsdRate.csv_file=(file)
		@csv_file = file
	end

	private

		def EurUsdRate.csv_load_from_uri
			begin
				open(CSV_URI)		
			rescue
			end
		end

		def EurUsdRate.fill_in_db
			begin
				@@data = CSV.read(@csv_file)[HEADER_SIZE..-1] 
				@@data.reverse.each do |row|
					EurUsdRate.create(date: row[0], currency: row[-1])
				end
			rescue
			end
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def calculate
	end

	def compute
		@dates_cur = EurUsdRate.where("date >= :start_date AND date <= :end_date",
								{start_date: params[:start_date], end_date: params[:end_date]})
		@amount = params[:sum]
		if !@dates_cur.empty? && !@amount.empty?
			@answers = EurUsdRate.exchange(params[:sum].to_f, get_currencies(@dates_cur))
		else
			flash[:error] = "Something went wrong. Please, choose another dates, check your amount or load rates form ECB!"
			redirect_to root_url
		end
	end

	def reload
		EurUsdRate.perform
		if EurUsdRate.data.empty?
			flash[:error] = "Please try in another time!"
			redirect_to root_url
		else
			flash[:success] = "Your data is updated!"
			redirect_to root_url
		end
	end

	private
		def get_currencies(dates_cur)
			res = []
			dates_cur.each { |cur| res << cur.currency }
			res
		end
end

app/helpers/application_helper.rb
module ApplicationHelper	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
	<html>
	<head>
		<title>Currency Rate | <%= yield(:title) %></title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<% flash.each do |key, value| %>
	  		<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
		<%= debug(params) if Rails.env.development? %>
	</body>
</html>

app/views/static_pages/calculate.html.erb
<% provide(:title, 'EUR to USD') %>
<h1>EUR/USD</h1>

<div class="row">
	<div class="span6 offset6">
		<p>This action will take 10 minutes. Please do not refresh the page!</p>
		<%= form_tag(reload_path) do %>
			<p>
				<%= submit_tag "Load from ECB", class: "btn" %>
			</p>
		<% end %>
	</div>
	<div class="span6 offset6">
		<p>Input your sum, check dates, click button below.</p>
		<%= form_tag(compute_path) do %>			
			<p>
				<%= label_tag :sum, "Amount of EUR:" %>
				<%= text_field_tag :sum %>
			</p>

			<p>
				<%= label_tag :start_date, "From" %>
				<%= date_field_tag :start_date %>

				<%= label_tag :end_date, "to" %>
				<%=date_field_tag :end_date %>
			</p>
			<p>				
				<%= submit_tag "Compute", class: "btn btn-large btn-primary" %>
			</p>
		<% end %>
	</div>
	<div>
		
	</div>
</div>

app/views/static_pages/compute.html.erb
<% provide(:title, 'Unswers') %>
<h1>You can change <%= @amount %> EUR to the next sum:</h1>
<%= link_to "Back", root_path %>
<ul class="answers">
	<% @dates_cur.length.times do |i| %>
		<li>
			<%= @dates_cur[i].date %> | <%= number_with_precision(@answers[i], :precision => 2)%>			
		</li>
	<% end %>
</ul>
<%= link_to "Back", root_path %>